public class PostalBranchDetails 
{
    Public string Name{get;set;}
    Public string Description{get;set;}
    Public string BranchType{get;set;}
    Public string DeliveryStatus{get;set;}
    Public string Circle{get;set;}
    Public string District{get;set;}
    Public string Division{get;set;}
    Public string Region{get;set;}
    Public string Block{get;set;}
    Public string State{get;set;}
    Public string Country{get;set;}
    Public string Pincode{get;set;}
}